# script to test service path support of HITS

use LWP::Curl;
$token = $ARGV[0]; # set token

@paths = qw(
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StaffAssignments?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StaffPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentContactPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentContactRelationships?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentDailyAttendances?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentPersonals/{STUDENTPERSONAL}/StudentDailyAttendances?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/StudentSchoolEnrollments?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/TeachingGroups?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/TimeTableCells?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/TimeTableSubjects?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/{SCHOOLINFO}/TimeTables?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StaffPersonals/{STAFFPERSONAL}/ScheduledActivitys?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StaffPersonals/{STAFFPERSONAL}/TeachingGroups?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/{STUDENTPERSONAL}/ScheduledActivitys?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/{STUDENTPERSONAL}/SchoolInfos/{SCHOOLINFO}/StudentDailyAttendances?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/{STUDENTPERSONAL}/StudentContactPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/{STUDENTPERSONAL}/StudentDailyAttendances?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/{STUDENTPERSONAL}/TeachingGroups?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TeachingGroups/{TEACHINGGROUP}/ScheduledActivitys?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TeachingGroups/{TEACHINGGROUP}/StaffPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TeachingGroups/{TEACHINGGROUP}/StudentPersonals?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TimeTableSubjects/{TIMETABLESUBJECT}/TeachingGroups?navigationPage=1&navigationPageSize=5&access_token={TOKEN}&authenticationMethod=Basic
);

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentPersonals/StudentPersonal?access_token=$token&authenticationMethod=Basic' -d '<StudentPersonal> <LocalId>S1234567</LocalId> <StateProvinceId>ABC1234</StateProvinceId> <PersonInfo> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Fred</GivenName> <FullName>Fred Smith</FullName> </Name> <Demographics> <Sex>1</Sex> </Demographics> <EmailList> <Email Type="01">fsmith\@yahoo.com</Email> <Email Type="02">freddy\@gmail.com</Email> </EmailList> </PersonInfo> <MostRecent> <YearLevel> <Code>P</Code> </YearLevel> </MostRecent> </StudentPersonal>'`;
($studentpersonal_refid) = $curl =~ m/<StudentPersonal RefId="([^"]+)"/;
die "no studentpersonal_refid returned from post\n" unless $studentpersonal_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/SchoolInfos/SchoolInfo?access_token=$token&authenticationMethod=Basic' -d '<SchoolInfo> <LocalId>01011234</LocalId> <StateProvinceId>01011234</StateProvinceId> <SchoolName>Lincoln Secondary College</SchoolName> <SchoolType>Pri/Sec</SchoolType> <SchoolEmailList> <Email Type="01">jmiller\@lsc.vic.edu.au</Email> </SchoolEmailList> <AddressList> <Address Type="0123" Role="012B"> <Street> <StreetNumber>23</StreetNumber> <StreetName>Nicholson Street</StreetName > </Street> <City>Carnegie</City> <StateProvince>VIC</StateProvince> <PostalCode>3004</PostalCode> </Address>  </AddressList> <OperationalStatus>O</OperationalStatus> <SchoolSector>NG</SchoolSector> </SchoolInfo>'`;
($schoolinfo_refid) = $curl =~ m/<SchoolInfo RefId="([^"]+)"/;
die "no schoolinfo_refid returned from post\n" unless $schoolinfo_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StaffPersonals/StaffPersonal?access_token=$token&authenticationMethod=Basic' -d '<StaffPersonal> <LocalId>946379881</LocalId> <StateProvinceId>C2345681</StateProvinceId> <PersonInfo> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Fred</GivenName> </Name> <Demographics> <Sex>1</Sex> </Demographics> <EmailList> <Email Type="01">fsmith\@yahoo.com</Email> <Email Type="02">freddy\@gmail.com</Email> </EmailList> </PersonInfo> <EmploymentStatus>A</EmploymentStatus> </StaffPersonal>'`;
($staffpersonal_refid) = $curl =~ m/<StaffPersonal RefId="([^"]+)"/;
die "no staffpersonal_refid returned from post\n" unless $staffpersonal_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/RoomInfos/RoomInfo?access_token=$token&authenticationMethod=Basic' -d '<RoomInfo> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <RoomNumber>101</RoomNumber> <StaffList> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> </StaffList> <Description>Room 101</Description> <Building>Main A</Building> <HomeroomNumber>10-HR-A</HomeroomNumber> <Size>400</Size> <Capacity>35</Capacity> <RoomType>Classroom</RoomType> </RoomInfo>'`;
($roominfo_refid) = $curl =~ m/<RoomInfo RefId="([^"]+)"/;
die "no roominfo_refid returned from post\n" unless $roominfo_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TimeTableSubjects/TimeTableSubject?access_token=$token&authenticationMethod=Basic' -d '<TimeTableSubject> <SubjectLocalId>07AR</SubjectLocalId> <AcademicYear> <Code>7</Code> </AcademicYear> <SubjectShortName>7 ART</SubjectShortName> <SubjectLongName>Year 7 Art</SubjectLongName> <SubjectType>E</SubjectType> <ProposedMaxClassSize>15</ProposedMaxClassSize> <ProposedMinClassSize>10</ProposedMinClassSize> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolLocalId>32718</SchoolLocalId> <Semester>1</Semester > <SchoolYear>2009</SchoolYear> </TimeTableSubject>'`;
($timetablesubject_refid) = $curl =~ m/<TimeTableSubject RefId="([^"]+)"/;
die "no timetablesubject_refid returned from post\n" unless $timetablesubject_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TeachingGroups/TeachingGroup?access_token=$token&authenticationMethod=Basic' -d '<TeachingGroup> <SchoolYear>2008</SchoolYear> <LocalId>20087ASPN</LocalId> <ShortName>7A SPN</ShortName> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <StudentList> <TeachingGroupStudent> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <StudentLocalId>SMI001</StudentLocalId> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Peter</GivenName> </Name> </TeachingGroupStudent> </StudentList> <TeacherList> <TeachingGroupTeacher> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <StaffLocalId>SMI1</StaffLocalId> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Thomas</GivenName> </Name> <Association>Class Teacher</Association> </TeachingGroupTeacher> </TeacherList> <TeachingGroupPeriodList> <TeachingGroupPeriod> <DayId>M</DayId> <PeriodId>2</PeriodId> </TeachingGroupPeriod> <TeachingGroupPeriod> <DayId>F</DayId> <PeriodId>6</PeriodId> </TeachingGroupPeriod> </TeachingGroupPeriodList> </TeachingGroup>'`;
($teachinggroup_refid) = $curl =~ m/<TeachingGroup RefId="([^"]+)"/;
die "no teachinggroup_refid returned from post\n" unless $teachinggroup_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentSchoolEnrollments/StudentSchoolEnrollment?access_token=$token&authenticationMethod=Basic' -d '<StudentSchoolEnrollment> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <MembershipType>01</MembershipType> <TimeFrame>C</TimeFrame> <SchoolYear>2004</SchoolYear> <EntryDate>2004-01-29</EntryDate> <YearLevel> <Code>10</Code> </YearLevel> <FTE>1.00</FTE> <FTPTStatus>01</FTPTStatus> <StudentSubjectChoiceList> <StudentSubjectChoice> <PreferenceNumber>1</PreferenceNumber> <SubjectLocalId>212</SubjectLocalId> </StudentSubjectChoice> <StudentSubjectChoice> <PreferenceNumber>2</PreferenceNumber> <SubjectLocalId>124</SubjectLocalId> </StudentSubjectChoice> </StudentSubjectChoiceList> </StudentSchoolEnrollment>'`;
($studentschoolenrollment_refid) = $curl =~ m/<StudentSchoolEnrollment RefId="([^"]+)"/;
die "no studentschoolenrollment_refid returned from post\n" unless $studentschoolenrollment_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StaffAssignments/StaffAssignment?access_token=$token&authenticationMethod=Basic' -d '<StaffAssignment> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolYear>2008</SchoolYear> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <Description>VCE English Teacher</Description> <PrimaryAssignment>Y</PrimaryAssignment> <JobStartDate>2000-09-05</JobStartDate> <JobEndDate>2001-06-25</JobEndDate> <JobFTE>1.00</JobFTE> <JobFunction>Teacher</JobFunction> <StaffActivity> <Code>1100</Code> </StaffActivity> <YearLevels> <YearLevel> <Code>11</Code> </YearLevel> <YearLevel> <Code>12</Code> </YearLevel> </YearLevels> </StaffAssignment>'`;
($staffassignment_refid) = $curl =~ m/<StaffAssignment RefId="([^"]+)"/;
die "no staffassignment_refid returned from post\n" unless $staffassignment_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentSchoolEnrollments/StudentSchoolEnrollment?access_token=$token&authenticationMethod=Basic' -d '<StudentSchoolEnrollment> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <MembershipType>01</MembershipType> <TimeFrame>C</TimeFrame> <SchoolYear>2004</SchoolYear> <EntryDate>2004-01-29</EntryDate> <YearLevel> <Code>10</Code> </YearLevel> <FTE>1.00</FTE> <FTPTStatus>01</FTPTStatus> <StudentSubjectChoiceList> <StudentSubjectChoice> <PreferenceNumber>1</PreferenceNumber> <SubjectLocalId>212</SubjectLocalId> </StudentSubjectChoice> <StudentSubjectChoice> <PreferenceNumber>2</PreferenceNumber> <SubjectLocalId>124</SubjectLocalId> </StudentSubjectChoice> </StudentSubjectChoiceList> </StudentSchoolEnrollment>'`;
($studentschoolenrollment_refid) = $curl =~ m/<StudentSchoolEnrollment RefId="([^"]+)"/;
die "no studentschoolenrollment_refid returned from post\n" unless $studentschoolenrollment_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentDailyAttendances/StudentDailyAttendance?access_token=$token&authenticationMethod=Basic' -d '<StudentDailyAttendance> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <Date>2014-11-24</Date> <SchoolYear>2014</SchoolYear> <DayValue>Full</DayValue> <AttendanceCode> <Code>SomeCode</Code> <OtherCodeList> <OtherCode codeset="Local">SomeOtherCode</OtherCode> </OtherCodeList> </AttendanceCode> <AttendanceStatus>Full</AttendanceStatus> <TimeIn>09:00:00</TimeIn> <TimeOut>15:30:00</TimeOut> <AbsenceValue>0.0</AbsenceValue> <AttendanceNote>Was at School</AttendanceNote> </StudentDailyAttendance>'`;
($studentdailyattendance_refid) = $curl =~ m/<StudentDailyAttendance RefId="([^"]+)"/;
die "no studentdailyattendance_refid returned from post\n" unless $studentdailyattendance_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentContactPersonals/StudentContactPersonal?access_token=$token&authenticationMethod=Basic' -d '<StudentContactPersonal> <LocalId>LocalId</LocalId> <PersonInfo> <Name> <Title>Mr</Title> <FamilyName>Tester</FamilyName> <GivenName>Fred</GivenName> <MiddleName>Middle</MiddleName> <PreferredFamilyName>PTester</PreferredFamilyName> <PreferredGivenName>PFred</PreferredGivenName> <FullName>Fred Tester</FullName> </Name> <Demographics/> <AddressList> <Address Type="0123" Role="012B"> <Street> <Line1>123 Address Line One</Line1> <Line2>Address Line Two</Line2> </Street> <City>Perth</City> <StateProvince>WA</StateProvince> <PostalCode>6000</PostalCode> <GridLocation> <Latitude>-31.952693</Latitude> <Longitude>115.871971</Longitude> </GridLocation> </Address> <Address Type="0123" Role="012B"> <Street> <Line1>234 Address Line One</Line1> </Street> <City>Perth</City> <StateProvince>WA</StateProvince> <PostalCode>6000</PostalCode> <GridLocation> <Latitude>-31.952693</Latitude> <Longitude>115.871971</Longitude> </GridLocation> </Address> </AddressList> <PhoneNumberList> <PhoneNumber> <Number>+61400000000</Number> </PhoneNumber> </PhoneNumberList> <EmailList> <Email Type="06">the.email\@not.a.real.domain</Email> </EmailList> </PersonInfo> <EmploymentType>1</EmploymentType> <SchoolEducationalLevel>4</SchoolEducationalLevel> <NonSchoolEducation>7</NonSchoolEducation> </StudentContactPersonal>'`;
($studentcontactpersonal_refid) = $curl =~ m/<StudentContactPersonal RefId="([^"]+)"/;
die "no studentcontactpersonal_refid returned from post\n" unless $studentcontactpersonal_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/StudentContactRelationships/StudentContactRelationship?access_token=$token&authenticationMethod=Basic' -d '<StudentContactRelationship StudentPersonalRefId="$studentpersonal_refid"> <Relationship> <Code>01</Code> </Relationship> <ContactFlags> <ParentLegalGuardian>Y</ParentLegalGuardian> <PickupRights>Y</PickupRights> <LivesWith>Y</LivesWith> <AccessToRecords>Y</AccessToRecords> <EmergencyContact>Y</EmergencyContact> <HasCustody>Y</HasCustody> <DisciplinaryContact>Y</DisciplinaryContact> <PrimaryCareProvider>Y</PrimaryCareProvider> <FeesBilling>Y</FeesBilling> <FamilyMail>Y</FamilyMail> <InterventionOrder>N</InterventionOrder> </ContactFlags> </StudentContactRelationship>'`;
($studentcontactrelationship_refid) = $curl =~ m/<StudentContactRelationship[^>]* StudentContactRelationshipRefId="([^"]+)"/;
die "no studentcontactrelationship_refid returned from post\n" unless $studentcontactrelationship_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TimeTables/TimeTable?access_token=$token&authenticationMethod=Basic' -d '<TimeTable> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolYear>2008</SchoolYear> <LocalId>2008S1</LocalId> <Title>2008 Semester 1</Title> <DaysPerCycle>5</DaysPerCycle> <PeriodsPerDay>6</PeriodsPerDay> <TeachingPeriodsPerDay>5</TeachingPeriodsPerDay> <SchoolLocalId>01011234</SchoolLocalId> <SchoolName>Newest Secondary College</SchoolName> <TimeTableCreationDate>2008-02-01</TimeTableCreationDate> <StartDate>2008-01-30</StartDate> <EndDate>2008-06-20</EndDate> <TimeTableDayList> <TimeTableDay> <DayId>1</DayId> <DayTitle>Monday</DayTitle> <TimeTablePeriodList> <TimeTablePeriod> <PeriodId>1</PeriodId> <PeriodTitle>P1</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>2</PeriodId> <PeriodTitle>P2</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>3</PeriodId> <PeriodTitle>P3</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>4</PeriodId> <PeriodTitle>P4</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>5</PeriodId> <PeriodTitle>P5</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>6</PeriodId> <PeriodTitle>P6</PeriodTitle> </TimeTablePeriod> </TimeTablePeriodList> </TimeTableDay> <TimeTableDay> <DayId>2</DayId> <DayTitle>Tuesday</DayTitle> <TimeTablePeriodList> <TimeTablePeriod> <PeriodId>1</PeriodId> <PeriodTitle>P1</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>2</PeriodId> <PeriodTitle>P2</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>3</PeriodId> <PeriodTitle>P3</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>4</PeriodId> <PeriodTitle>P4</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>5</PeriodId> <PeriodTitle>P5</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>6</PeriodId> <PeriodTitle>P6</PeriodTitle> </TimeTablePeriod> </TimeTablePeriodList> </TimeTableDay> </TimeTableDayList> </TimeTable>'`;
($timetable_refid) = $curl =~ m/<TimeTable[^>]* RefId="([^"]+)"/;
die "no timetable_refid returned from post\n" unless $timetable_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/TimeTableCells/TimeTableCell?access_token=$token&authenticationMethod=Basic' -d '<TimeTableCell> <TimeTableRefId>$timetable_refid</TimeTableRefId> <TimeTableSubjectRefId>$timetablesubject_refid</TimeTableSubjectRefId> <TeachingGroupRefId>$teachinggroup_refid</TeachingGroupRefId> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <TimeTableLocalId>2008S1</TimeTableLocalId> <SubjectLocalId>07AR</SubjectLocalId> <TeachingGroupLocalId>20087ASPN 2008S1</TeachingGroupLocalId> <RoomNumber>101</RoomNumber> <StaffLocalId>946379881</StaffLocalId> <DayId>1</DayId> <PeriodId>1</PeriodId> <CellType>T</CellType> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolLocalId>01011234</SchoolLocalId> </TimeTableCell>'`;
($timetablecell_refid) = $curl =~ m/<TimeTableCell[^>]* RefId="([^"]+)"/;
die "no timetablecell_refid returned from post\n" unless $timetablecell_refid;

$curl = `curl -i -X POST 'http://hitstest.dev.nsip.edu.au/SIF3InfraREST/hits/requests/ScheduledActivitys/ScheduledActivity?access_token=$token&authenticationMethod=Basic' -d '<ScheduledActivity> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <TimeTableCellRefId>$timetablecell_refid</TimeTableCellRefId> <DayId>1</DayId> <PeriodId>1</PeriodId> <TimeTableRefId>$timetable_refid</TimeTableRefId> <ActivityDate>2014-10-10</ActivityDate> <StartTime>12:05:00</StartTime> <FinishTime>13:30:00</FinishTime> <CellType>Classroom</CellType> <TimeTableSubjectRefId>$timetablesubject_refid</TimeTableSubjectRefId> <TeacherList> <TeacherCover> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <StaffLocalId>US8923</StaffLocalId> <StartTime>12:05:00</StartTime> <FinishTime>13:00:00</FinishTime> <Credit>In-lieu</Credit> <Supervision>MinimalSupervision</Supervision> <Weighting>0.5</Weighting> </TeacherCover> </TeacherList> <RoomList> <RoomInfoRefId>$roominfo_refid</RoomInfoRefId> </RoomList> <ActivityType>Incursion</ActivityType> <StudentList> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> </StudentList><TeachingGroupList> <TeachingGroupRefId>$teachinggroup_refid</TeachingGroupRefId> </TeachingGroupList> </ScheduledActivity>'`;
($scheduledactivity_refid) = $curl =~ m/<ScheduledActivity[^>]* RefId="([^"]+)"/;
die "no scheduledactivity_refid returned from post\n" unless $scheduledactivity_refid;

$failed = 0;
foreach $url (@paths) {
  $url =~ s/\{TOKEN\}/$token/;
  $url =~ s/\{STUDENTPERSONAL\}/$studentpersonal_refid/;
  $url =~ s/\{SCHOOLINFO\}/$schoolinfo_refid/;
  $url =~ s/\{STAFFPERSONAL\}/$staffpersonal_refid/;
  $url =~ s/\{TEACHINGGROUP\}/$teachinggroup_refid/;
  $url =~ s/\{TIMETABLESUBJECT\}/$timetablesubject_refid/;
  $curl = `curl -i -s -X GET "$url"`;
  if ($curl =~ m/HTTP\/1.1 204 No Content/) {
    printf "Failed query: $url\n";
    $failed++;
  }
}
printf "%d service path queries failed out of %d\n", $failed, scalar @paths;
