# script to test service path support of HITS

use LWP::Curl;
$token = $ARGV[0]; # set token

$baseURL = "http://hitstest.dev.nsip.edu.au";
#$baseURL = "http://hits.nsip.edu.au";

$studentpersonal_refid = get("StudentPersonal", qq{<StudentPersonal> <LocalId>S1234567</LocalId> <StateProvinceId>ABC1234</StateProvinceId> <PersonInfo> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Fred</GivenName> <FullName>Fred Smith</FullName> </Name> <Demographics> <Sex>1</Sex> </Demographics> <EmailList> <Email Type="01">fsmith\@yahoo.com</Email> <Email Type="02">freddy\@gmail.com</Email> </EmailList> </PersonInfo> <MostRecent> <YearLevel> <Code>P</Code> </YearLevel> </MostRecent> </StudentPersonal>}, "RefId");
$schoolinfo_refid = get("SchoolInfo", qq{<SchoolInfo> <LocalId>01011234</LocalId> <StateProvinceId>01011234</StateProvinceId> <SchoolName>Lincoln Secondary College</SchoolName> <SchoolType>Pri/Sec</SchoolType> <SchoolEmailList> <Email Type="01">jmiller\@lsc.vic.edu.au</Email> </SchoolEmailList> <AddressList> <Address Type="0123" Role="012B"> <Street> <StreetNumber>23</StreetNumber> <StreetName>Nicholson Street</StreetName > </Street> <City>Carnegie</City> <StateProvince>VIC</StateProvince> <PostalCode>3004</PostalCode> </Address>  </AddressList> <OperationalStatus>O</OperationalStatus> <SchoolSector>NG</SchoolSector> </SchoolInfo>}, "RefId");
$staffpersonal_refid = get("StaffPersonal", qq{<StaffPersonal> <LocalId>946379881</LocalId> <StateProvinceId>C2345681</StateProvinceId> <PersonInfo> <Name Type="LGL"> <FamilyName>Smith</FamilyName> <GivenName>Fred</GivenName> </Name> <Demographics> <Sex>1</Sex> </Demographics> <EmailList> <Email Type="01">fsmith\@yahoo.com</Email> <Email Type="02">freddy\@gmail.com</Email> </EmailList> </PersonInfo> <EmploymentStatus>A</EmploymentStatus> </StaffPersonal>}, "RefId");
$timetablesubject_refid = get("TimeTableSubject", qq{<TimeTableSubject> <SubjectLocalId>07AR</SubjectLocalId> <AcademicYear> <Code>7</Code> </AcademicYear> <SubjectShortName>7 ART</SubjectShortName> <SubjectLongName>Year 7 Art</SubjectLongName> <SubjectType>E</SubjectType> <ProposedMaxClassSize>15</ProposedMaxClassSize> <ProposedMinClassSize>10</ProposedMinClassSize> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolLocalId>32718</SchoolLocalId> <Semester>1</Semester > <SchoolYear>2009</SchoolYear> </TimeTableSubject>}, "RefId");
$studentschoolenrollment_refid = get("StudentSchoolEnrollment", qq{<StudentSchoolEnrollment> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <MembershipType>01</MembershipType> <TimeFrame>C</TimeFrame> <SchoolYear>2004</SchoolYear> <EntryDate>2004-01-29</EntryDate> <YearLevel> <Code>10</Code> </YearLevel> <FTE>1.00</FTE> <FTPTStatus>01</FTPTStatus> <StudentSubjectChoiceList> <StudentSubjectChoice> <PreferenceNumber>1</PreferenceNumber> <SubjectLocalId>212</SubjectLocalId> </StudentSubjectChoice> <StudentSubjectChoice> <PreferenceNumber>2</PreferenceNumber> <SubjectLocalId>124</SubjectLocalId> </StudentSubjectChoice> </StudentSubjectChoiceList> </StudentSchoolEnrollment>}, "RefId");
$staffassignment_refid = get("StaffAssignment", qq{<StaffAssignment> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolYear>2008</SchoolYear> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <Description>VCE English Teacher</Description> <PrimaryAssignment>Y</PrimaryAssignment> <JobStartDate>2000-09-05</JobStartDate> <JobEndDate>2001-06-25</JobEndDate> <JobFTE>1.00</JobFTE> <JobFunction>Teacher</JobFunction> <StaffActivity> <Code>1100</Code> </StaffActivity> <YearLevels> <YearLevel> <Code>11</Code> </YearLevel> <YearLevel> <Code>12</Code> </YearLevel> </YearLevels> </StaffAssignment>}, "RefId");
$studentcontactpersonal_refid = get("StudentContactPersonal", qq{<StudentContactPersonal> <LocalId>LocalId</LocalId> <PersonInfo> <Name> <Title>Mr</Title> <FamilyName>Tester</FamilyName> <GivenName>Fred</GivenName> <MiddleName>Middle</MiddleName> <PreferredFamilyName>PTester</PreferredFamilyName> <PreferredGivenName>PFred</PreferredGivenName> <FullName>Fred Tester</FullName> </Name> <Demographics/> <AddressList> <Address Type="0123" Role="012B"> <Street> <Line1>123 Address Line One</Line1> <Line2>Address Line Two</Line2> </Street> <City>Perth</City> <StateProvince>WA</StateProvince> <PostalCode>6000</PostalCode> <GridLocation> <Latitude>-31.952693</Latitude> <Longitude>115.871971</Longitude> </GridLocation> </Address> <Address Type="0123" Role="012B"> <Street> <Line1>234 Address Line One</Line1> </Street> <City>Perth</City> <StateProvince>WA</StateProvince> <PostalCode>6000</PostalCode> <GridLocation> <Latitude>-31.952693</Latitude> <Longitude>115.871971</Longitude> </GridLocation> </Address> </AddressList> <PhoneNumberList> <PhoneNumber> <Number>+61400000000</Number> </PhoneNumber> </PhoneNumberList> <EmailList> <Email Type="06">the.email\@not.a.real.domain</Email> </EmailList> </PersonInfo> <EmploymentType>1</EmploymentType> <SchoolEducationalLevel>4</SchoolEducationalLevel> <NonSchoolEducation>7</NonSchoolEducation> </StudentContactPersonal>}, "RefId");
$timetable_refid = get("TimeTable", qq{<TimeTable> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolYear>2008</SchoolYear> <LocalId>2008S1</LocalId> <Title>2008 Semester 1</Title> <DaysPerCycle>5</DaysPerCycle> <PeriodsPerDay>6</PeriodsPerDay> <TeachingPeriodsPerDay>5</TeachingPeriodsPerDay> <SchoolLocalId>01011234</SchoolLocalId> <SchoolName>Newest Secondary College</SchoolName> <TimeTableCreationDate>2008-02-01</TimeTableCreationDate> <StartDate>2008-01-30</StartDate> <EndDate>2008-06-20</EndDate> <TimeTableDayList> <TimeTableDay> <DayId>1</DayId> <DayTitle>Monday</DayTitle> <TimeTablePeriodList> <TimeTablePeriod> <PeriodId>1</PeriodId> <PeriodTitle>P1</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>2</PeriodId> <PeriodTitle>P2</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>3</PeriodId> <PeriodTitle>P3</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>4</PeriodId> <PeriodTitle>P4</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>5</PeriodId> <PeriodTitle>P5</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>6</PeriodId> <PeriodTitle>P6</PeriodTitle> </TimeTablePeriod> </TimeTablePeriodList> </TimeTableDay> <TimeTableDay> <DayId>2</DayId> <DayTitle>Tuesday</DayTitle> <TimeTablePeriodList> <TimeTablePeriod> <PeriodId>1</PeriodId> <PeriodTitle>P1</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>2</PeriodId> <PeriodTitle>P2</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>3</PeriodId> <PeriodTitle>P3</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>4</PeriodId> <PeriodTitle>P4</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>5</PeriodId> <PeriodTitle>P5</PeriodTitle> </TimeTablePeriod> <TimeTablePeriod> <PeriodId>6</PeriodId> <PeriodTitle>P6</PeriodTitle> </TimeTablePeriod> </TimeTablePeriodList> </TimeTableDay> </TimeTableDayList> </TimeTable>}, "RefId");
$timetablecell_refid = get("TimeTableCell", qq{<TimeTableCell> <TimeTableRefId>$timetable_refid</TimeTableRefId> <TimeTableSubjectRefId>$timetablesubject_refid</TimeTableSubjectRefId> <TeachingGroupRefId>$teachinggroup_refid</TeachingGroupRefId> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <TimeTableLocalId>2008S1</TimeTableLocalId> <SubjectLocalId>07AR</SubjectLocalId> <TeachingGroupLocalId>20087ASPN 2008S1</TeachingGroupLocalId> <RoomNumber>101</RoomNumber> <StaffLocalId>946379881</StaffLocalId> <DayId>1</DayId> <PeriodId>1</PeriodId> <CellType>T</CellType> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <SchoolLocalId>01011234</SchoolLocalId> </TimeTableCell>}, "RefId");
$scheduledactivity_refid = get("ScheduledActivity", qq{<ScheduledActivity> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <TimeTableCellRefId>$timetablecell_refid</TimeTableCellRefId> <DayId>1</DayId> <PeriodId>1</PeriodId> <TimeTableRefId>$timetable_refid</TimeTableRefId> <ActivityDate>2014-10-10</ActivityDate> <StartTime>12:05:00</StartTime> <FinishTime>13:30:00</FinishTime> <CellType>Classroom</CellType> <TimeTableSubjectRefId>$timetablesubject_refid</TimeTableSubjectRefId> <TeacherList> <TeacherCover> <StaffPersonalRefId>$staffpersonal_refid</StaffPersonalRefId> <StaffLocalId>US8923</StaffLocalId> <StartTime>12:05:00</StartTime> <FinishTime>13:00:00</FinishTime> <Credit>In-lieu</Credit> <Supervision>MinimalSupervision</Supervision> <Weighting>0.5</Weighting> </TeacherCover> </TeacherList> <RoomList> <RoomInfoRefId>$roominfo_refid</RoomInfoRefId> </RoomList> <ActivityType>Incursion</ActivityType> <StudentList> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> </StudentList><TeachingGroupList> <TeachingGroupRefId>$teachinggroup_refid</TeachingGroupRefId> </TeachingGroupList> </ScheduledActivity>}, "RefId");



$personalisedplan_refid = post("PersonalisedPlan", qq{<PersonalisedPlan xmlns="http://www.sifassociation.org/datamodel/au/3.4"> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <PersonalisedPlanCategory>M</PersonalisedPlanCategory> <PersonalisedPlanStartDate>2017-11-01</PersonalisedPlanStartDate> <PersonalisedPlanEndDate>2019-11-10</PersonalisedPlanEndDate> <PersonalisedPlanReviewDate>2018-11-10</PersonalisedPlanReviewDate> <PersonalisedPlanNotes>This Student is allergic to cashews.</PersonalisedPlanNotes> <DocumentList> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> </DocumentList> <AssociatedAttachment>http://example.com</AssociatedAttachment> </PersonalisedPlan>}, "RefId");
$wellbeingalert_refid = post("WellbeingAlert", qq{ <WellbeingAlert> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <Date>2017-11-01</Date> <WellbeingAlertStartDate>2017-11-01</WellbeingAlertStartDate> <WellbeingAlertEndDate>2017-11-01</WellbeingAlertEndDate> <WellbeingAlertCategory>M</WellbeingAlertCategory> <WellbeingAlertDescription>This Student is allergic to peanuts</WellbeingAlertDescription> <EnrolmentRestricted>Yes</EnrolmentRestricted> <AlertAudience>Me</AlertAudience> <AlertKeyContact>Fred</AlertKeyContact> </WellbeingAlert>}, "RefId");
$wellbeingresponse_refid = post("WellbeingResponse", qq{ <WellbeingResponse> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <Date>2017-11-01</Date> <WellbeingResponseStartDate>2017-11-01</WellbeingResponseStartDate> <WellbeingResponseEndDate>2017-11-10</WellbeingResponseEndDate> <WellbeingResponseCategory>S</WellbeingResponseCategory> <WellbeingResponseNotes>This Student is to be withdrawn.</WellbeingResponseNotes> <PersonInvolvementList> <PersonInvolvement> <PersonRefId SIF_RefObject="StudentPersonal">$studentpersonal_refid</PersonRefId> <ShortName>Fred</ShortName> <HowInvolved>Bellicose</HowInvolved> </PersonInvolvement> </PersonInvolvementList> <Suspension> <SuspensionCategory>E</SuspensionCategory> <WithdrawalTimeList> <Withdrawal> <WithdrawalDate>2018-01-01</WithdrawalDate> <WithdrawalStartTime>12:09:09</WithdrawalStartTime> <WithdrawalEndTime>12:09:59</WithdrawalEndTime> <TimeTableSubjectRefId>$timetablesubject_refid</TimeTableSubjectRefId> <ScheduledActivityRefId>$scheduledactivity_refid</ScheduledActivityRefId> <TimeTableCellRefId>$timetablecell_refid</TimeTableCellRefId> </Withdrawal> </WithdrawalTimeList> <Duration>0.01</Duration> <AdvisementDate>2016-02-02</AdvisementDate> <ResolutionMeetingTime>2016-02-02T00:00:01</ResolutionMeetingTime> <ResolutionNotes>Note 1</ResolutionNotes> <EarlyReturnDate>2018-02-02</EarlyReturnDate> <Status>R</Status> </Suspension> <Detention> <DetentionCategory>AR</DetentionCategory> <DetentionDate>2018-09-01</DetentionDate> <DetentionLocation>Desk</DetentionLocation> <DetentionNotes>Note 2</DetentionNotes> <Status>R</Status> </Detention> <PlanRequired> <PlanRequiredList> <Plan> <PersonalisedPlanRefId>$personalisedplan_refid</PersonalisedPlanRefId> <PlanNotes>Required</PlanNotes> </Plan> </PlanRequiredList> <Status>R</Status> </PlanRequired> <Award> <AwardDate>2015-02-03</AwardDate> <AwardType>Promotion</AwardType> <AwardDescription>This is an Award</AwardDescription> <AwardNotes>Note 3</AwardNotes> <Status>R</Status> </Award> <OtherResponse> <OtherResponseDate>1999-01-08</OtherResponseDate> <OtherResponseType>Other Response 2</OtherResponseType> <OtherResponseDescription>This is an Other Response</OtherResponseDescription> <OtherResponseNotes>Note 4</OtherResponseNotes> <Status>R</Status> </OtherResponse> <DocumentList> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> </DocumentList> </WellbeingResponse> }, "RefId"); 
$wellbeingevent_refid = post("WellbeingEvent", qq{ <WellbeingEvent> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <EventId>3</EventId> <WellbeingEventNotes>Things happened</WellbeingEventNotes> <WellbeingEventCategoryClass>P</WellbeingEventCategoryClass> <WellbeingEventCategoryList> <WellbeingEventCategory> <EventCategory>B1</EventCategory> <WellbeingEventSubCategoryList> <WellbeingEventSubCategory>B1a</WellbeingEventSubCategory> <WellbeingEventSubCategory>B1b</WellbeingEventSubCategory> </WellbeingEventSubCategoryList> </WellbeingEventCategory> <WellbeingEventCategory> <EventCategory>B2</EventCategory> <WellbeingEventSubCategoryList> <WellbeingEventSubCategory>B2a</WellbeingEventSubCategory> <WellbeingEventSubCategory>B2b</WellbeingEventSubCategory> </WellbeingEventSubCategoryList> </WellbeingEventCategory> </WellbeingEventCategoryList> <ReportingStaffRefId>$staffpersonal_refid</ReportingStaffRefId> <WellbeingEventLocationDetails> <EventLocation>C</EventLocation> <Class>History 10A</Class> <FurtherLocationNotes>Back of classroom</FurtherLocationNotes> </WellbeingEventLocationDetails> <WellbeingEventCreationTimeStamp>2018-01-01T09:09:09</WellbeingEventCreationTimeStamp> <WellbeingEventDate>2017-11-01</WellbeingEventDate> <WellbeingEventTime>04:09:09</WellbeingEventTime> <WellbeingEventDescription>There was an incident</WellbeingEventDescription> <WellbeingEventTimePeriod>AM</WellbeingEventTimePeriod> <ConfidentialFlag>Y</ConfidentialFlag> <PersonInvolvementList> <PersonInvolvement> <PersonRefId SIF_RefObject="StudentPersonal">$studentpersonal_refid</PersonRefId> <ShortName>Fred</ShortName> <HowInvolved>Bellicose</HowInvolved> </PersonInvolvement> </PersonInvolvementList> <FollowUpActionList> <FollowUpAction> <WellbeingResponseRefId>$wellbeingresponse_refid</WellbeingResponseRefId> <FollowUpDetails>Investigate further</FollowUpDetails> <FollowUpActionCategory>Followup</FollowUpActionCategory> </FollowUpAction> </FollowUpActionList> <Status>R</Status> <DocumentList> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> </DocumentList> </WellbeingEvent> }, "RefId");
$wellbeingcharacteristic_refid = post("WellbeingCharacteristic", qq{ <WellbeingCharacteristic> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$schoolinfo_refid</SchoolInfoRefId> <WellbeingCharacteristicClassification>D</WellbeingCharacteristicClassification> <WellbeingCharacteristicStartDate>2017-11-01</WellbeingCharacteristicStartDate> <WellbeingCharacteristicEndDate>2017-11-10</WellbeingCharacteristicEndDate> <WellbeingCharacteristicReviewDate>2017-11-05</WellbeingCharacteristicReviewDate> <WellbeingCharacteristicNotes>This Student has a special need.</WellbeingCharacteristicNotes> <WellbeingCharacteristicCategory>S</WellbeingCharacteristicCategory> <WellbeingCharacteristicSubCategory>MCM-15</WellbeingCharacteristicSubCategory> <LocalCharacteristicCode>XYZ</LocalCharacteristicCode> <CharacteristicSeverity>Severe</CharacteristicSeverity> <DailyManagement>Daily</DailyManagement> <EmergencyManagement>Emergency</EmergencyManagement> <EmergencyResponsePlan>Plan</EmergencyResponsePlan> <Trigger>Trigger</Trigger> <ConfidentialFlag>Y</ConfidentialFlag> <Alert>Y</Alert> <MedicationList> <Medication> <MedicationName>Pennicilin</MedicationName> <Dosage>30ml</Dosage> <Frequency>Twice daily</Frequency> <AdministrationInformation>With due caution</AdministrationInformation> <Method>Orally</Method> </Medication> </MedicationList> <DocumentList> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> </DocumentList> </WellbeingCharacteristic>}, "RefId");
$wellbeingappeal_refid = post("WellbeingAppeal", qq{ <WellbeingAppeal> <StudentPersonalRefId>$studentpersonal_refid</StudentPersonalRefId> <SchoolInfoRefId>$Schoolinfo_refid</SchoolInfoRefId> <WellbeingResponseRefId>$wellbeingresponse_refid</WellbeingResponseRefId> <LocalAppealId>XYZ</LocalAppealId> <AppealStatusCode>SU</AppealStatusCode> <Date>2017-11-01</Date> <AppealNotes>This Appeal was successful.</AppealNotes> <AppealOutcome>This Appeal was successful.</AppealOutcome> <DocumentList> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> <Document> <Location>Desk</Location> <Sensitivity>1</Sensitivity> <URL>http://www.example2.com</URL> <DocumentType>Plan</DocumentType> <DocumentReviewDate>2017-01-01</DocumentReviewDate> <DocumentDescription>I am a document</DocumentDescription> </Document> </DocumentList> </WellbeingAppeal>}, "RefId");



sub post($$$) {
  my ($object, $body, $refid) = @_;
  #print qq<curl -i -X POST '$baseURL/SIF3InfraREST/hits/requests/${object}s/$object?access_token=$token&authenticationMethod=Basic' -d '$body'>;
  my $curl = `curl -i -X POST '$baseURL/SIF3InfraREST/hits/requests/${object}s/$object?access_token=$token&authenticationMethod=Basic' -d '$body'`;
  my ($studentpersonal_refid) = $curl =~ m/<$object [^>]*$refid="([^"]+)"/;
  die "no $object RefId returned from post\n" unless $studentpersonal_refid or ($object eq "StudentAttendanceTimeList" or $object eq "NAPTestlet" or $object eq "NAPStudentResponseSet");
  print "Successfully created $object, with RefId $studentpersonal_refid\n";
  return $studentpersonal_refid;
}

sub get($$$) {
  my ($object, $body, $refid) = @_;
  print qq<curl -i -X GET '$baseURL/SIF3InfraREST/hits/requests/${object}s?access_token=$token&navigationPage=1&navigationPageSize=5&authenticationMethod=Basic'>;
  my $curl = `curl -i -X GET '$baseURL/SIF3InfraREST/hits/requests/${object}s?access_token=$token&navigationPage=1&navigationPageSize=5&authenticationMethod=Basic'`;
  my ($studentpersonal_refid) = $curl =~ m/<$object [^>]*$refid="([^"]+)"/;
  die "no $object RefId returned from post\n" unless $studentpersonal_refid or ($object eq "StudentAttendanceTimeList" or $object eq "NAPTestlet" or $object eq "NAPStudentResponseSet");
  return $studentpersonal_refid;
}

